
Vagrant.configure(2) do |config|

  config.vm.box = "opentable/win-2012r2-standard-amd64-nocm"
#  config.vm.guest= :windows

  config.vm.provision :shell, path: "iis.ps1"
  config.vm.provision :shell, path: "delete-default-iis-website.ps1"
  config.vm.provision :shell, path: "chocolatey.ps1"

 # config.vm.boot_timeout = 600

  config.vm.network :private_network, ip: "192.168.56.20"

 # config.vm.provider "virtualbox" do |vb|

  #  vb.cpus = 2
   # vb.memory = 2048
  # end
end
