#q -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#lampserver
Vagrant.configure(2) do |config|


  config.vm.box = "centos/7"

  config.vm.network :private_network, ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
     # Don't boot with headless mode
     # vb.gui = true

     # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "1280"]
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
   end

config.vm.synced_folder "html", "/home/vagrant/public_html"
config.vm.synced_folder "scripts", "/home/vagrant/scriptsVagrant"
 #config.vm.synced_folder "www/", "/var/www/", :owner => "www-data", :group => "www-data", :mount_options => [ "dmode=775", "fmode=666" ]

  config.vm.provision :shell, path: "lampInstall.sh"
  config.vm.provision :shell, path: "sec.sh"


end
