#q -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#filserver
Vagrant.configure(2) do |config|


  config.vm.box = "ubuntu/trusty64"

  config.vm.network :private_network, ip: "192.168.56.17"


  config.vm.provision :shell, path: "monoserverInstall.sh"
# onfig.vm.provision :shell, path: "sec.sh"
config.vm.synced_folder "scripts", "/home/vagrant/scripts"


end
