#q -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#javaserver
Vagrant.configure(2) do |config|


  config.vm.box = "centos/7"

  config.vm.network :private_network, ip: "192.168.56.11"

  config.vm.provider "virtualbox" do |vb|
     # Don't boot with headless mode
     # vb.gui = true

     # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "1280"]
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
   end

  config.vm.synced_folder "java", "/home/vagrant/java"
  config.vm.synced_folder "mysqlconnector", "/home/vagrant/mysqlconnectorVagrant"
  config.vm.provision :shell, path: "javaInstall.sh"
  config.vm.provision :shell, path: "tomcatlogin.sh"

end
